name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install libdragon dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            python3-pip \
            git \
            wget \
            libpng-dev \
            pkg-config \
            ca-certificates

      - name: Install libdragon toolchain
        run: |
          TOOLCHAIN_URL="https://github.com/DragonMinded/libdragon/releases/download/toolchain-continuous-prerelease/gcc-toolchain-mips64-x86_64.deb"
          wget --quiet "$TOOLCHAIN_URL" -O /tmp/libdragon-toolchain.deb
          sudo apt-get install -y /tmp/libdragon-toolchain.deb
          echo "/opt/libdragon/bin" >> "$GITHUB_PATH"
          echo "N64_INST=/opt/libdragon" >> "$GITHUB_ENV"

      - name: Build ROM
        run: make

      - name: Clean build artifacts
        run: make clean
